spring:
  application:
    name: hystrix-dashboard

server:
  port: 7979

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
